### PR TITLE
Bump `nix` dependency to `0.24`

### PR DESCRIPTION
**Pull request by MarijnS95**
Even though `nix 0.25` is already out, all Wayland crates are still on `0.24` and having `wl-clipboard-rs` match saves duplicate dependencies:

```console
$ cargo tree -i nix
nix v0.24.2
├── wayland-client v0.29.5
│   ├── wayland-protocols v0.29.5
│   │   └── wl-clipboard-rs v0.6.0 (./wl-clipboard-rs)
│   │   [dev-dependencies]
│   │   └── wl-clipboard-rs v0.6.0 (./wl-clipboard-rs)
│   └── wl-clipboard-rs v0.6.0 (./wl-clipboard-rs)
├── wayland-commons v0.29.5
│   ├── wayland-client v0.29.5 (*)
│   ├── wayland-protocols v0.29.5 (*)
│   └── wayland-server v0.29.5
│       └── wayland-protocols v0.29.5 (*)
│       [dev-dependencies]
│       └── wl-clipboard-rs v0.6.0 (./wl-clipboard-rs)
├── wayland-server v0.29.5 (*)
└── wl-clipboard-rs v0.6.0 (./wl-clipboard-rs)
```

### CODE REVIEW

**Comment by YaLTeR** [comment]
Thanks!

**Comment by MarijnS95** [comment]
Thanks for merging all these PRs! Can we get a release with them (before e.g. `nix 0.25` starts to become prevalent and an update is needed here again)?

**Comment by YaLTeR** [comment]
Yeah, I can do that. Is there anything else or is it good to go?

**Comment by MarijnS95** [comment]
@YaLTeR Thanks - I don't need anything else and it doesn't seem like there's any other open PR actively making progression.

**Comment by YaLTeR** [comment]
Published wl-clipboard{,-tools} 0.7.0.

**Pull request merged**
